### ISSUE TITLE
任务看板，日历，可以开发发布下么？

### ISSUE THREAD

**Issue by xukai504087493** [Zeekg-zk/Collaborative-Platform#1]
请问：任务看板，日历
这两个模块可以开发发布一下么？还是比较实用的，感谢您，已star

**Comment by zach-xing** [comment]
Hhh，首先还是感谢您认可，不过目前还有其他事情，没有时间，所以暂时没有计划去开发这两部分😂

不过原来是计划的利用这些lib来实现的：

- 任务看板，是利用拖动组件来实现的，原来计划是使用这个来实现的：https://react-beautiful-dnd.netlify.app/?path=/story/board--simple
- 日历，其实可以直接看antd里面的日历组件，主要是记录某天有那些待做事项。

（额外插一嘴，可以将上面两部分结合起来，比如点击日历中某一天时，旁边弹出一个浮动框，可以拖动改变此天任务的优先级之类的😂😂）

**Comment by zach-xing** [comment]
> 请问：任务看板，日历 这两个模块可以开发发布一下么？还是比较实用的，感谢您，已star

Hhh，首先还是感谢您认可，不过目前还有其他事情，没有时间，所以暂时没有计划去开发这两部分😂

不过原来是计划的利用这些lib来实现的：

- 任务看板，是利用拖动组件来实现的，原来计划是使用这个来实现的：https://react-beautiful-dnd.netlify.app/?path=/story/board--simple
- 日历，其实可以直接看antd里面的日历组件，主要是记录某天有那些待做事项。

（额外插一嘴，可以将上面两部分结合起来，比如点击日历中某一天时，旁边弹出一个浮动框，可以拖动改变此天任务的优先级之类的😂😂）
