### ISSUE TITLE
可以提供下完整的建表sql吗？

### ISSUE THREAD

**Issue by magnificent0121** [Zeekg-zk/Collaborative-Platform#2]
我在使用prisma同步表结构到mysql的时候似乎遇到了一些问题， 请问可以提供下建表sql吗？

**Comment by zach-xing** [comment]
https://github.com/zach-xing/Collaborative-Platform/blob/master/server/prisma/schema.prisma

这里都有表的结构，至于 sql 都是 Prisma 的命令帮生成的
